apiVersion: v1
kind: Service
metadata:
    name: helloworld-service
    namespace: helloworldNS
spec:
    selector:
        app: helloworld
    ports:
        - name: application
        protocol: TCP
        port: 8080
        targetPort: 8080
    type: ClusterIP